"""Forward evaluation: compile the node tree into a real armature.

Two-pass execution, because Blender requires it:
  1. Edit-mode pass: create/update the armature object + edit bones
     (head/tail/roll/parent/connect).
  2. Pose-mode pass: apply constraints to pose bones, which can only be
     added once the armature exists.

Re-running the build on an already-built output updates in place (matched by
armature object name and by bone name) instead of duplicating.
"""

import bpy
from mathutils import Vector

from .core import EvalContext, unique_names


def find_output_node(tree):
    from .nodes import ArmatureOutputNode

    for node in tree.nodes:
        if node.bl_idname == ArmatureOutputNode.bl_idname:
            return node
    return None


def evaluate_tree(tree, strict=True):
    """Evaluate from the output node backward. Returns (name, list[BoneDef]).

    ``strict`` (the Build button) raises on an empty graph so the user gets an
    error. Live update passes ``strict=False``: an emptied graph is not a
    failure, it is a graph that now produces nothing, and the armature has to
    follow it down -- same as a Shader Editor material going black when you
    delete the shader node.
    """
    output = find_output_node(tree)
    if output is None:
        if strict:
            raise RuntimeError("No Armature Output node in the tree")
        return "", []
    ctx = EvalContext()
    bones = output.eval_bones(ctx)
    if not bones:
        if strict:
            raise RuntimeError("Armature Output node has no bones wired into it")
        return output.target_name(), []

    # Deduplicate: shared lineages (a parent emitted through several branches)
    # may appear multiple times. Keep the LAST occurrence of each name so
    # downstream modifiers (DeformGroup etc.) win, then restore order.
    by_name = {}
    order = []
    for b in bones:
        if b.name not in by_name:
            order.append(b.name)
        by_name[b.name] = b
    bones = [by_name[n] for n in order]
    return output.target_name(), unique_names(bones)


OWNER_TREE_KEY = "an_owner_tree"
OWNER_NODE_KEY = "an_owner_node"
# Bones the graph shaped on its last run (Custom Shapes Only mode), so the
# next run can strip controllers whose nodes are gone.


def tag_owner(obj, tree, node):
    """Record that this armature object was generated by a node.

    Without this there is no way to tell a rig the graph created (delete the
    node, delete the rig) from a rig the user made and merely pointed the
    graph at (delete the node, leave the rig alone).
    """
    obj[OWNER_TREE_KEY] = tree.name
    obj[OWNER_NODE_KEY] = node.name


def owned_objects(tree_name, node_name=None):
    """Armature objects generated by a tree, or by one node of it."""
    out = []
    for obj in bpy.data.objects:
        if obj.type != "ARMATURE" or obj.get(OWNER_TREE_KEY) != tree_name:
            continue
        if node_name is not None and obj.get(OWNER_NODE_KEY) != node_name:
            continue
        out.append(obj)
    return out


def _drop_owned_objects(tree):
    """Queue every armature this tree generated for removal."""
    from .tree import queue_object_removal

    for obj in owned_objects(tree.name):
        queue_object_removal(obj.name)


from .apply.legacy_full import (  # noqa: E402
    _activate,
    _edit_mode_pass,
    _ensure_object_mode,
    _get_or_create_armature_object,
    _pose_mode_pass,
)


# tree name -> signature of the bone list its last Full Rig build produced.
# Module level so it resets on reload, which is the safe direction: a stale
# entry could skip a needed rebuild, a missing one only costs one rebuild.
_full_signatures = {}


def _rest_signature(bone_defs):
    """Changes when the bones themselves change -- what needs Edit mode."""
    return hash(
        repr(
            [
                (b.name, b.head, b.tail, b.roll, b.parent, b.use_connect,
                 b.use_deform, repr(b.constraints), repr(b.shape))
                for b in bone_defs
            ]
        )
    )


def _pose_signature(bone_defs):
    """Changes when only the graph's requested pose changes.

    Kept apart from the rest signature because posing needs no mode change at
    all: ``pbone.matrix`` is writable from Object, Pose or anywhere else. A
    pose-only edit must never defer, or adjusting a control from the node
    while in Pose mode would do nothing -- which is exactly what it did.
    """
    return hash(
        repr(
            [
                (b.name, b.pose_location, b.pose_rotation, b.pose_scale,
                 b.pose_offset, b.pose_rotation_offset)
                for b in bone_defs
            ]
        )
    )


# tree name -> bones the last Full Rig build posed, so a bone whose node was
# deleted goes back to rest instead of keeping the pose for ever.
_full_posed = {}


def _apply_graph_pose(obj, bone_defs, tree_name=""):
    """Apply the pose the Transform-category nodes asked for.

    Modify mode gets this through the record pipeline. Full Rig owns its
    armature and has no record to diff against, so the same pose pass is run
    directly -- without this, every Bone, Position, Rotation, Transform and
    Snap node was silently discarded in Full Rig mode.
    """
    from . import bridge
    from .apply.pose_display import pose_pass
    from .apply.writer import Writer
    from .model.types import TransformDef

    if obj is None or obj.pose is None:
        return 0
    transforms = {}
    for bdef in bone_defs:
        transform = bridge._transform_from_graph(bdef)
        if not transform.is_empty():
            transforms[bdef.name] = transform
    # Bones posed last time and not now: an empty transform sends them to rest.
    for name in _full_posed.get(tree_name, ()):
        transforms.setdefault(name, TransformDef())
    _full_posed[tree_name] = {n for n, t in transforms.items() if not t.is_empty()}

    writer = Writer()
    pose_pass(obj, transforms, writer)
    for message in writer.errors[:3]:
        print(f"[Armature Nodes] {message}")
    return writer.writes


def _live_nodes(tree):
    """The tree's nodes and those of every node group it runs: a node inside
    a group poses the rig as much as one outside it."""
    from .groups import trees_in_use

    for current in trees_in_use(tree):
        yield from current.nodes


def _follow_live(tree):
    for node in _live_nodes(tree):
        if hasattr(node, "follow_live"):
            try:
                node.follow_live()
            except Exception as exc:  # noqa: BLE001
                print(f"[Armature Nodes] Live link failed on '{node.name}': {exc}")


def _note_built(tree):
    """Whatever the linked bones look like now is the graph's own doing."""
    for node in _live_nodes(tree):
        if hasattr(node, "note_built"):
            try:
                node.note_built()
            except Exception as exc:  # noqa: BLE001
                print(f"[Armature Nodes] Live snapshot failed on '{node.name}': {exc}")


def _remember_mode():
    obj = bpy.context.active_object
    return (obj.name, obj.mode) if obj is not None else (None, "OBJECT")


def _restore_mode(built_obj, remembered):
    """Live updates must not yank the user out of Pose/Edit mode.

    Only the Full Rig path needs this now: it rebuilds edit bones, so it has
    no choice but to change mode. Modify mode never calls it.
    """
    name, mode = remembered
    if mode == "OBJECT" or name is None or built_obj is None:
        return
    if name != built_obj.name:
        return
    if built_obj.mode == mode:
        return  # already there; mode_set would emit a pointless depsgraph update
    try:
        bpy.context.view_layer.objects.active = built_obj
        bpy.ops.object.mode_set(mode=mode)
    except RuntimeError as exc:
        print(f"[Armature Nodes] Could not restore {mode} mode: {exc}")


def _modify_pass(tree, name, bone_defs):
    """Modify mode: restore-then-apply against the rig's own record.

    The whole of Modify mode is four lines of intent -- read the record, fold
    the graph into it, diff, apply -- because every case that used to need a
    branch is now the same case. An unplugged Input evaluates to nothing,
    ``overlay`` returns the record unchanged, the diff is empty, and the
    pipeline restores whatever the last build wrote. Nothing is special.
    """
    from . import bridge
    from .apply import pipeline
    from .store import record as record_store
    from .store import touched as touched_store

    obj = bpy.data.objects.get(name)
    if obj is None or obj.type != "ARMATURE":
        tree.is_dirty = False
        return None

    if record_store.needs_migration(obj):
        # First build is where a legacy record is upgraded; reads before this
        # point are deliberately non-destructive.
        try:
            record_store.persist_migration(obj)
            # Loud, once. A v1 record was captured by the implementation that
            # captured lazily, so it may well have recorded an already-modified
            # rig as the original -- and migration cannot tell. Saying so is
            # the only honest option; silently blessing it is how a stripped
            # rig becomes permanent.
            print(
                f"[Armature Nodes] Upgraded '{obj.name}' record to v2. "
                "This record came from an older version that could capture a "
                "rig after it had been modified. If the rig looks wrong, "
                "regenerate it and use Capture Rig State on the fresh one."
            )
            tree.last_error = (
                "Record migrated from v1 - verify the rig, then Capture if wrong"
            )
        except Exception as exc:  # noqa: BLE001
            print(f"[Armature Nodes] Could not upgrade record: {exc}")

    base = record_store.read(obj)
    if base is None:
        tree.last_error = f"'{obj.name}' is not bound - use Bind Rig"
        tree.is_dirty = False
        return None

    # Edit mode makes ``armature.bones`` stale -- it is the edit_bones that
    # are live -- so applying now would read and write nothing real. Skip and
    # let leaving Edit mode retrigger the build.
    if obj.mode == "EDIT":
        tree.last_error = ""
        return obj

    target = bridge.overlay(base, bone_defs)
    # No mode switching here, deliberately. Custom shapes, pose, constraints
    # and collection membership are all writable from Pose mode, and the one
    # thing that is not -- rest geometry -- is handled by the pipeline, which
    # enters Edit mode only when a rest field actually changed and restores
    # the mode afterwards.
    #
    # Forcing Object mode around every build is what made Pose mode unusable:
    # mode_set is an operator, so each flip emitted a depsgraph update, which
    # scheduled another build, which flipped again. Most builds write nothing
    # at all, so the whole dance was for a no-op.
    result = pipeline.apply(obj, base, target, touched_store.read(obj))
    _note_built(tree)

    tree.last_error = "; ".join(result.errors[:2]) if result.errors else ""
    tree.is_dirty = False
    return obj


def build_armature_from_tree(tree, strict=False):
    """Apply the tree to its armature (full build, shapes-only update, or
    teardown of what the graph no longer produces).

    Returns the armature object, or None when the graph produces nothing.
    Called automatically by live update.
    """
    output = find_output_node(tree)
    if output is None:
        if strict:
            raise RuntimeError("No Armature Output node in the tree")
        # The Output node is gone: so is everything it generated.
        _drop_owned_objects(tree)
        tree.is_dirty = False
        return None

    # Anything the user did to a live-linked bone since the last look goes
    # into its node first, so this build evaluates with it instead of
    # snapping the bone back.
    _follow_live(tree)
    name, bone_defs = evaluate_tree(tree, strict=strict)
    mode = getattr(output, "mode", "MODIFY")

    if mode == "MODIFY":
        return _modify_pass(tree, name, bone_defs)

    if not bone_defs:
        # Full Rig owns its armature, so a graph that produces nothing means
        # the armature it generated should go with it.
        for obj in owned_objects(tree.name, output.name):
            from .tree import queue_object_removal

            queue_object_removal(obj.name)
        tree.is_dirty = False
        return None

    # A copied node graph must never overwrite the source rig. The original
    # bound tree has a live Armature Input pointer; pasted/copied graphs do
    # not, so give them a fresh target on first evaluation.
    has_live_source = any(
        node.bl_idname == "ArmatureNodesInputNode"
        and getattr(node, "source", None) is not None
        for node in tree.nodes
    )
    existing = bpy.data.objects.get(name)
    bound_here = existing is not None and (
        existing.get(OWNER_TREE_KEY) == tree.name
        or getattr(existing, "armature_nodes_tree", None) == tree
    )
    if not has_live_source and existing is not None and not bound_here:
        name = _unique_armature_name(name)
        output.armature_name = name
    elif bound_here and existing.get(OWNER_TREE_KEY) != tree.name:
        tag_owner(existing, tree, output)
    # Full Rig rebuilds edit bones, so unlike Modify it has no choice but to
    # change mode. Two guards keep that from fighting the user:
    #
    # 1. Nothing to do -> do nothing. Without this, every depsgraph tick ran a
    #    full EDIT + POSE + OBJECT cycle, and each mode_set is an operator
    #    that emits another depsgraph update, which scheduled another build.
    #    That loop is why Pose mode snapped straight back to Object.
    # 2. Never mid-interaction. Yanking someone out of Pose or Edit to rebuild
    #    bones they are in the middle of using is hostile; defer until they
    #    are back in Object mode (sync.watch_armature_mode re-dirties then).
    rest_sig = _rest_signature(bone_defs)
    pose_sig = _pose_signature(bone_defs)
    previous = _full_signatures.get(tree.name)
    rest_changed = previous is None or previous[0] != rest_sig
    pose_changed = previous is None or previous[1] != pose_sig

    if existing is not None and not rest_changed and not pose_changed:
        tree.is_dirty = False
        return existing  # nothing to do; running anyway is what caused the loop

    obj = existing
    if rest_changed:
        # Rebuilding bones needs Edit mode, so it cannot run while the user is
        # in the middle of Pose or Edit. Defer -- sync.watch_armature_mode
        # re-dirties the tree when they leave.
        if existing is not None and existing.mode != "OBJECT":
            return existing
        remembered = _remember_mode()
        _ensure_object_mode()
        obj, created = _get_or_create_armature_object(name)
        if created or obj.get(OWNER_TREE_KEY) == tree.name:
            tag_owner(obj, tree, output)
        _edit_mode_pass(obj, bone_defs)
        _pose_mode_pass(obj, bone_defs)
        _restore_mode(obj, remembered)

    # Pose last, and from whatever mode the user is in: writing pbone.matrix
    # needs no operator, so this is safe mid-pose and must not be deferred.
    if pose_changed or rest_changed:
        _apply_graph_pose(obj, bone_defs, tree.name)
        _note_built(tree)

    _full_signatures[tree.name] = (rest_sig, pose_sig)
    tree.is_dirty = False
    return obj
