"""Forward evaluation: compile the node tree into a real armature.

Two-pass execution, because Blender requires it:
  1. Edit-mode pass: create/update the armature object + edit bones
     (head/tail/roll/parent/connect).
  2. Pose-mode pass: apply constraints to pose bones, which can only be
     added once the armature exists.

Re-running the build on an already-built output updates in place (matched by
armature object name and by bone name) instead of duplicating.
"""

import bpy
from mathutils import Vector

from .core import EvalContext, unique_names


def find_output_node(tree):
    from .nodes import ArmatureOutputNode

    for node in tree.nodes:
        if node.bl_idname == ArmatureOutputNode.bl_idname:
            return node
    return None


def evaluate_tree(tree, strict=True):
    """Evaluate from the output node backward. Returns (name, list[BoneDef]).

    ``strict`` (the Build button) raises on an empty graph so the user gets an
    error. Live update passes ``strict=False``: an emptied graph is not a
    failure, it is a graph that now produces nothing, and the armature has to
    follow it down -- same as a Shader Editor material going black when you
    delete the shader node.
    """
    output = find_output_node(tree)
    if output is None:
        if strict:
            raise RuntimeError("No Armature Output node in the tree")
        return "", []
    ctx = EvalContext()
    bones = output.eval_bones(ctx)
    if not bones:
        if strict:
            raise RuntimeError("Armature Output node has no bones wired into it")
        return output.armature_name or "Armature", []

    # Deduplicate: shared lineages (a parent emitted through several branches)
    # may appear multiple times. Keep the LAST occurrence of each name so
    # downstream modifiers (DeformGroup etc.) win, then restore order.
    by_name = {}
    order = []
    for b in bones:
        if b.name not in by_name:
            order.append(b.name)
        by_name[b.name] = b
    bones = [by_name[n] for n in order]
    return output.armature_name or "Armature", unique_names(bones)


OWNER_TREE_KEY = "an_owner_tree"
OWNER_NODE_KEY = "an_owner_node"
# Bones the graph shaped on its last run (Custom Shapes Only mode), so the
# next run can strip controllers whose nodes are gone.
SHAPED_BONES_KEY = "an_shaped_bones"


def tag_owner(obj, tree, node):
    """Record that this armature object was generated by a node.

    Without this there is no way to tell a rig the graph created (delete the
    node, delete the rig) from a rig the user made and merely pointed the
    graph at (delete the node, leave the rig alone).
    """
    obj[OWNER_TREE_KEY] = tree.name
    obj[OWNER_NODE_KEY] = node.name


def owned_objects(tree_name, node_name=None):
    """Armature objects generated by a tree, or by one node of it."""
    out = []
    for obj in bpy.data.objects:
        if obj.type != "ARMATURE" or obj.get(OWNER_TREE_KEY) != tree_name:
            continue
        if node_name is not None and obj.get(OWNER_NODE_KEY) != node_name:
            continue
        out.append(obj)
    return out


def _drop_owned_objects(tree):
    """Queue every armature this tree generated for removal."""
    from .tree import queue_object_removal

    for obj in owned_objects(tree.name):
        queue_object_removal(obj.name)


def _ensure_object_mode():
    if bpy.context.mode != "OBJECT" and bpy.context.active_object:
        bpy.ops.object.mode_set(mode="OBJECT")


def _target_collection():
    # bpy.context.collection is None inside timer callbacks; fall back to the
    # scene root collection so live updates can still link new objects.
    collection = bpy.context.collection
    if collection is None:
        collection = bpy.context.scene.collection
    return collection


def _get_or_create_armature_object(name):
    obj = bpy.data.objects.get(name)
    if obj is not None and obj.type == "ARMATURE":
        return obj, False
    arm_data = bpy.data.armatures.new(name)
    obj = bpy.data.objects.new(name, arm_data)
    _target_collection().objects.link(obj)
    return obj, True


def _activate(obj):
    """Make ``obj`` the active, visible, selected object so mode_set polls true."""
    view_layer = bpy.context.view_layer
    if obj.name not in view_layer.objects:
        # Object exists but is not in this view layer (e.g. excluded
        # collection): link it to the scene root so it can be edited.
        bpy.context.scene.collection.objects.link(obj)
    try:
        if obj.hide_get():
            obj.hide_set(False)
    except RuntimeError:
        pass
    obj.hide_viewport = False
    view_layer.objects.active = obj
    obj.select_set(True)


def _edit_mode_pass(obj, bone_defs):
    """Create/update edit bones from BoneDefs, matched by name."""
    _activate(obj)
    bpy.ops.object.mode_set(mode="EDIT")
    try:
        edit_bones = obj.data.edit_bones
        wanted = {b.name for b in bone_defs}

        # Remove bones no longer produced by the graph.
        for eb in list(edit_bones):
            if eb.name not in wanted:
                edit_bones.remove(eb)

        # Create/update all bones first (positions), then parent links,
        # so parenting never references a bone that does not exist yet.
        for b in bone_defs:
            eb = edit_bones.get(b.name)
            if eb is None:
                eb = edit_bones.new(b.name)
            eb.head = b.head
            eb.tail = b.tail
            eb.roll = b.roll
            eb.use_deform = b.use_deform
            eb.envelope_distance = b.envelope_distance
            eb.envelope_weight = b.envelope_weight

        for b in bone_defs:
            eb = edit_bones[b.name]
            if b.parent and b.parent in edit_bones:
                eb.parent = edit_bones[b.parent]
                eb.use_connect = b.use_connect
            else:
                eb.parent = None
                eb.use_connect = False
    finally:
        bpy.ops.object.mode_set(mode="OBJECT")


def _resolve_target(name, self_obj):
    """Constraint targets are stored by object name. A rig rebuilt from a
    snapshot may carry a different object name, so targets that pointed at
    the original armature are redirected to the armature being built."""
    obj = bpy.data.objects.get(name)
    if obj is None and self_obj is not None:
        return self_obj
    return obj


def _apply_constraint(pose_bone, cdef, self_obj=None):
    try:
        con = pose_bone.constraints.new(cdef.type)
    except TypeError as exc:
        print(f"[Armature Nodes] Cannot create constraint {cdef.type}: {exc}")
        return
    if cdef.name:
        con.name = cdef.name
    params = dict(cdef.params)
    # Set 'targets' collection (Armature constraint) separately.
    targets = params.pop("targets", None)
    # Object pointers first so dependent props (subtarget) validate.
    for key in ("target", "pole_target", "space_object"):
        if key in params:
            value = _resolve_target(params.pop(key), self_obj)
            if value is not None:
                try:
                    setattr(con, key, value)
                except (AttributeError, TypeError) as exc:
                    print(f"[Armature Nodes] Skipped constraint param {key}: {exc}")
    for key, value in params.items():
        if isinstance(value, list):
            value = tuple(value)
        try:
            setattr(con, key, value)
        except (AttributeError, TypeError, ValueError) as exc:
            print(f"[Armature Nodes] Skipped constraint param {key}: {exc}")
    if targets and hasattr(con, "targets"):
        for t in targets:
            tgt = con.targets.new()
            tgt.target = _resolve_target(t.get("target", ""), self_obj)
            tgt.subtarget = t.get("subtarget", "")
            tgt.weight = t.get("weight", 1.0)


def _apply_shape(pbone, bdef):
    """Assign (or clear) the custom shape widget on a pose bone."""
    from .widgets import resolve_widget_for_bone

    shape = bdef.shape
    widget = resolve_widget_for_bone(shape, bdef.name) if shape else None
    if widget is None:
        pbone.custom_shape = None
        pbone.bone.show_wire = False
        return
    pbone.custom_shape = widget
    pbone.custom_shape_scale_xyz = shape.scale
    pbone.custom_shape_translation = shape.translation
    pbone.custom_shape_rotation_euler = shape.rotation
    pbone.use_custom_shape_bone_size = shape.scale_to_bone_length
    pbone.bone.show_wire = shape.show_wire
    if hasattr(pbone, "custom_shape_wire_width"):  # Blender 4.x+
        pbone.custom_shape_wire_width = shape.wire_width


def _pose_mode_pass(obj, bone_defs):
    """Clear graph-managed constraints and apply constraints + custom shapes."""
    _activate(obj)
    bpy.ops.object.mode_set(mode="POSE")
    try:
        defs_by_name = {b.name: b for b in bone_defs}
        for pbone in obj.pose.bones:
            bdef = defs_by_name.get(pbone.name)
            if bdef is None:
                continue
            for con in list(pbone.constraints):
                pbone.constraints.remove(con)
            for cdef in bdef.constraints:
                _apply_constraint(pbone, cdef, self_obj=obj)
            _apply_shape(pbone, bdef)
    finally:
        bpy.ops.object.mode_set(mode="OBJECT")


def _geometry_differs(bone, bdef, eps=1e-6):
    """True when a BoneDef's rest geometry/hierarchy no longer matches the
    armature bone -- i.e. the user edited it on a Custom Shape node."""
    if (Vector(bdef.head) - bone.head_local).length > eps:
        return True
    if (Vector(bdef.tail) - bone.tail_local).length > eps:
        return True
    parent = bone.parent.name if bone.parent else None
    if (bdef.parent or None) != parent:
        return True
    return bone.use_connect != bdef.use_connect or bone.use_deform != bdef.use_deform


def _edit_geometry_pass(obj, bone_defs):
    """Move/re-parent ONLY the given existing bones (no create/remove)."""
    _activate(obj)
    bpy.ops.object.mode_set(mode="EDIT")
    try:
        edit_bones = obj.data.edit_bones
        for b in bone_defs:
            eb = edit_bones.get(b.name)
            if eb is None:
                continue
            eb.head = b.head
            eb.tail = b.tail
            eb.roll = b.roll
            eb.use_deform = b.use_deform
            if b.parent and b.parent in edit_bones:
                eb.parent = edit_bones[b.parent]
                eb.use_connect = b.use_connect
            else:
                eb.parent = None
                eb.use_connect = False
    finally:
        bpy.ops.object.mode_set(mode="OBJECT")


def _clear_shape(pbone):
    """Strip the controller widget the graph previously put on this bone."""
    pbone.custom_shape = None
    pbone.custom_shape_scale_xyz = (1.0, 1.0, 1.0)
    pbone.custom_shape_translation = (0.0, 0.0, 0.0)
    pbone.custom_shape_rotation_euler = (0.0, 0.0, 0.0)
    pbone.use_custom_shape_bone_size = True
    pbone.bone.show_wire = False
    if hasattr(pbone, "custom_shape_wire_width"):
        pbone.custom_shape_wire_width = 1.0


def _shapes_only_pass(obj, bone_defs):
    """Update an EXISTING armature from its Custom Shape nodes only.

    Used for generated rigs (Rigify): the generator owns bones, constraints
    and drivers, so only bones that carry a ShapeDef are touched -- their
    widget, and their rest geometry/parent when a node edited it.

    The set of bones shaped on the previous run is remembered on the object
    so this pass is a real diff: a bone whose Custom Shape node was deleted,
    muted or filtered out loses its controller instead of silently keeping
    the stale one. That is what makes the generated rig live, not just the
    metarig.
    """
    shaped = [b for b in bone_defs if b.shape is not None]
    moved = [
        b
        for b in shaped
        if b.name in obj.data.bones and _geometry_differs(obj.data.bones[b.name], b)
    ]
    if moved:
        _edit_geometry_pass(obj, moved)

    previous = set(obj.get(SHAPED_BONES_KEY, ()))
    current = {b.name for b in shaped}
    stale = previous - current

    _activate(obj)
    bpy.ops.object.mode_set(mode="POSE")
    applied = 0
    cleared = 0
    try:
        for bone_name in stale:
            pbone = obj.pose.bones.get(bone_name)
            if pbone is None:
                continue
            _clear_shape(pbone)
            cleared += 1
        for bdef in shaped:
            pbone = obj.pose.bones.get(bdef.name)
            if pbone is None:
                print(f"[Armature Nodes] Rig has no bone '{bdef.name}', skipped")
                continue
            _apply_shape(pbone, bdef)
            applied += 1
    finally:
        bpy.ops.object.mode_set(mode="OBJECT")

    obj[SHAPED_BONES_KEY] = sorted(current)
    if cleared:
        print(f"[Armature Nodes] Removed {cleared} stale controller(s) from '{obj.name}'")
    return applied


def marker_pose_pass(tree, obj):
    """Pose every controller whose Custom Shape node has a marker wired in.

    Runs after the bones exist and are in place, because posing a bone writes
    a matrix resolved against its parent's evaluated transform. Markers drive
    the POSE only: rest geometry stays whatever the graph built, and moving a
    marker moves the control the way grabbing it in Pose mode would.

    A Custom Shape node with no marker wired in is skipped, so this costs
    nothing on graphs that do not use markers.
    """
    if obj is None or obj.type != "ARMATURE":
        return 0
    applied = 0
    for node in tree.nodes:
        if node.bl_idname != "ArmatureNodesCustomShapeNode":
            continue
        try:
            if node.apply_marker_pose(obj=obj):
                applied += 1
        except Exception as exc:  # noqa: BLE001
            print(f"[Armature Nodes] Marker pose failed on '{node.name}': {exc}")
    if applied:
        view_layer = getattr(bpy.context, "view_layer", None)
        if view_layer is not None:
            view_layer.update()
    return applied


def _remember_mode():
    obj = bpy.context.active_object
    return (obj.name, obj.mode) if obj is not None else (None, "OBJECT")


def _restore_mode(built_obj, remembered):
    """Live updates must not yank the user out of Pose/Edit mode."""
    name, mode = remembered
    if mode == "OBJECT" or name is None or name != built_obj.name:
        return
    try:
        bpy.context.view_layer.objects.active = built_obj
        bpy.ops.object.mode_set(mode=mode)
    except RuntimeError as exc:
        print(f"[Armature Nodes] Could not restore {mode} mode: {exc}")


def build_armature_from_tree(tree, strict=False):
    """Apply the tree to its armature (full build, shapes-only update, or
    teardown of what the graph no longer produces).

    Returns the armature object, or None when the graph produces nothing.
    Called automatically by live update.
    """
    output = find_output_node(tree)
    if output is None:
        if strict:
            raise RuntimeError("No Armature Output node in the tree")
        # The Output node is gone: so is everything it generated.
        _drop_owned_objects(tree)
        tree.is_dirty = False
        return None

    name, bone_defs = evaluate_tree(tree, strict=strict)
    if not bone_defs:
        # Nothing feeds the output any more. A generated rig goes away with
        # its source; a rig the user owns (shapes-only, or an object the graph
        # did not create) is left untouched.
        if getattr(output, "mode", "FULL") != "SHAPES_ONLY":
            for obj in owned_objects(tree.name, output.name):
                from .tree import queue_object_removal

                queue_object_removal(obj.name)
        else:
            # The last Custom Shape node is gone: strip every controller the
            # graph had put on the rig, but leave Rigify's bones alone.
            obj = bpy.data.objects.get(name)
            if obj is not None and obj.type == "ARMATURE" and obj.get(SHAPED_BONES_KEY):
                remembered = _remember_mode()
                _ensure_object_mode()
                _shapes_only_pass(obj, [])
                _restore_mode(obj, remembered)
        tree.is_dirty = False
        return None
    # A copied node graph must never overwrite the source rig. The original
    # bound tree has a live Armature Input pointer; pasted/copied graphs do
    # not, so give them a fresh target on first evaluation.
    has_live_source = any(
        node.bl_idname == "ArmatureNodesInputNode"
        and getattr(node, "source", None) is not None
        for node in tree.nodes
    )
    existing = bpy.data.objects.get(name)
    bound_here = existing is not None and (
        existing.get(OWNER_TREE_KEY) == tree.name
        or getattr(existing, "armature_nodes_tree", None) == tree
    )
    if not has_live_source and existing is not None and not bound_here:
        name = _unique_armature_name(name)
        output.armature_name = name
    elif bound_here and existing.get(OWNER_TREE_KEY) != tree.name:
        tag_owner(existing, tree, output)
    remembered = _remember_mode()
    _ensure_object_mode()

    if getattr(output, "mode", "FULL") == "SHAPES_ONLY":
        obj = bpy.data.objects.get(name)
        if obj is not None and obj.type == "ARMATURE":
            _shapes_only_pass(obj, bone_defs)
            marker_pose_pass(tree, obj)
            tree.is_dirty = False
            _restore_mode(obj, remembered)
            return obj
        # The armature this graph was decompiled from is gone. The nodes
        # carry the full bone/constraint/widget data, so rebuild it in full.
        print(
            f"[Armature Nodes] '{name}' not found; rebuilding it from the "
            f"graph ({len(bone_defs)} bones)"
        )

    obj, created = _get_or_create_armature_object(name)
    if created or obj.get(OWNER_TREE_KEY) == tree.name:
        tag_owner(obj, tree, output)
    _edit_mode_pass(obj, bone_defs)
    _pose_mode_pass(obj, bone_defs)
    marker_pose_pass(tree, obj)
    tree.is_dirty = False
    _restore_mode(obj, remembered)
    return obj
